cert:
  enabled: false

kube-prometheus-stack:
  ## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  ##
  grafana:
    # set cookies for backstage plugin integration
    grafana.ini:
      security:
        allow_embedding: 'true'
        cookie_samesite: none
        cookie_secure: 'true'
    ingress:
      ## If true, Grafana Ingress will be created
      ##
      enabled: true
      hosts: [grafana-127-0-0-1.nip.io]
      tls:
        - secretName: monitoring-server-tls
          hosts:
          - grafana-127-0-0-1.nip.io
    # # To make Grafana persistent (Using Statefulset)
    # #
    persistence:
      enabled: true
      type: sts
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      finalizers:
        - kubernetes.io/pvc-protection

    sidecar:
      datasources:
        searchNamespace:
          - monitoring
          - mimir
          
  kubeApiServer:
    serviceMonitor:
      metricRelabelings:
      - sourceLabels: [__name__]
        action: drop
        regex: apiserver_request_duration_seconds_bucket

    ## Settings affecting prometheusSpec
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
    ##
    prometheusSpec:
      ## If true, a nil or {} value for prometheus.prometheusSpec.serviceMonitorSelector will cause the
      ## prometheus resource to be created with selectors based on values in the helm deployment,
      ## which will also match the servicemonitors created
      ##        
      serviceMonitorSelectorNilUsesHelmValues: false

      # remote write to Grafana Mimir instance for central monitoring
      # since this prometheus instance lives in the same cluster as mimir, we cannot set the ingress hostname
      # since this points to 127.0.0.1 in the container.
      # so we set the internal service name
      remoteWrite:
        - url: http://sx-mimir-nginx.mimir.svc/api/v1/push
          name: kubeX-observability